name: CI

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    #   packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    - name: Verify tag on main branch
      run: |
        if [ "$(git rev-parse ${{ github.ref }})" != "$(git rev-parse origin/main)" ]; then
          echo "Tag is not on the head of the main branch. Aborting."
          exit 1
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Update K8s deployment image tag
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/}
        sed -i "s|image: ghcr.io/mswoo/test:.*|image: ghcr.io/mswoo/test:${TAG_VERSION}|" k8s/02-deployment.yaml
        
    - name: Commit updated deployment
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout main
        git add k8s/02-deployment.yaml
        git commit -m "Update image tag to ${GITHUB_REF#refs/tags/}" || exit 0
        git push origin main

