name: CI Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:          
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    - name: Verify tag on main branch
      run: |
        if [ "$(git rev-parse ${{ github.ref }})" != "$(git rev-parse origin/main)" ]; then
          echo "Tag is not on the head of the main branch. Aborting."
          exit 1
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest

  update-deployment-repo:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
    - name: Checkout deployment repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/test-deploy
        token: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Update K8s deployment image tag
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/}
        echo "Updating image tag to: $TAG_VERSION"
        
        # deployment.yaml에서 이미지 태그 업데이트
        sed -i "s|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${TAG_VERSION}|" k8s/deployment.yaml
        
        # 변경사항 확인
        echo "Updated deployment.yaml:"
        cat k8s/deployment.yaml | grep "image:"
        
    - name: Commit updated deployment
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 변경사항이 있는지 확인
        if git diff --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        git add k8s/deployment.yaml
        git commit -m "Update image tag to ${TAG_VERSION}"
        git push origin main
